#https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml
services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: bioacc
      POSTGRES_PASSWORD: bioacc
      POSTGRES_DB: bioacc
      PGDATA: '/data/postgres'
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'

    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      
      # - ./infra/initpg.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8543:8080
